owner: forwarded
repo: status

sites:
  - name: jtdowney.dev demo (HTTP)
    url: http://jtdowney.dev

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Forwarded Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - jtdowney
